---
title: "DanzAna"
---

<!-- :::{.derecha} -->
<!-- ```      -->
<!-- A la ilustradora de mi imaginación, -->
<!-- que sus trazos danzan por el lienzo -->
<!-- como bailarina por los pisos del ballet. -->

<!-- -Sergio Sclovich- -->
<!-- ```      -->
<!-- ::: -->


:::{.centrado}

Ana amaba danzar.

A la mañana la garra manaba, al alba acababa arrastrada.

Agazapada andaba tras danzar la lambada.

La cama la llamaba,

más las ganas bastaban para alzarla.

¿Tanta maná para nada? Patrañas,

amaba la lambada, nada más la llamaba.

:::

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

La mamá aclamaba: ─pará la danza, trabajá─.

Ana nada acataba. Danzaba, nada más.

Las patadas arrasaban la sala,

las zancadas machacaban la aljaba, mas nada la paraba.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

Harta hasta las nalgas la mamá grazna: ─¡ay! hada maga, pará la danza.

Calmá a Ana, aplacá la alharaca, basta ya, basta!─

Carla, hada maga aclamada, aclara: la danza parará, más la macana valdrá 
cara.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

A la mañana Ana nada danzaba, la cama abarcaba, calma, más nada pasaba.

Tras la sábana la parca cantaba.

─¡Ah! hada mala─ aclamaba la mamá. Carla a carcajadas andaba.

Amargada, la mamá, al alma manchada abrazaba.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

Tras la fachada andaba J'an.

Galán, marchaba a la alta armada.

─¡Pará!, salvá a Ana─ grazna la mamá.

─A la carga─ J'an aclama,

la maza a la palma agarrada, al hada Carla aplasta.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

La aclamada hada, achatada, ya las carcajadas callaba.

La parca alza al hada maga.

Agazapada avanzaba la parca alma.

Tramaba la danza atrapar,

más las fallas acaban al plan.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

La macana para calmar la danza amansaba.

Ana aclaraba a baja habla ─"las patas nada danzan, más la mala racha ya acaba"─.

Mamá la abraza.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

A la mañana, tras la hazaña, a la plaza pasan.

Mamá canta, J'an abraza al arpa, Ana danza.

Al alba, la paz manaba.

J'an la amaba, Ana abrazada andaba.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

Salvada, amada.

Hasta acá narra la carta

Danza, Ana danza.

