---
title: "JuAna"
---

:::{.derecha}
```     
A mi hada de las letras,
que con pasión y entusiasmo
me acompaña en mis aventuras literarias

-Sergio Sclovich-
```     
:::


Informe número 1614, 3/3/44: cambio de la órbita de Venus por Juan Astrónomo.

“La mañana del primero de febrero de 1944 detecté una anomalía en la órbita de Venus. Por extraño que parezca, lo vi fuera de su órbita esperada observándose de mayor tamaño conforme pasa el tiempo, de modo que se está acercando a nuestro planeta”. 

─Tengo que apurarme a publicar esto─ dijo Juan pensando en voz alta ─es mi oportunidad. Abuelo─ pensó mirando al cielo─ voy a poner tu nombre en la historia como siempre soñaste.

Juan siguió pensando en voz alta ─finalmente le daré un sentido trascendente a esa negligencia─ dijo concluyendo su mensaje a las estrellas. Resulta que Vladimir Schwartzman, el abuelo de Juan, había llegado al puerto de Buenos Aires en 1914 desde Rusia con su esposa e hijo. Entre el bullicio de cientos de inmigrantes arribando y las diferencias idiomáticas, los trabajadores en la recepción de la aduana confundieron el apellido de Vladimir con su profesión: astrónomo. Fue así como su verdadera identidad fue borrada y reemplazada por otra.

El tres de marzo de 1944 Ana estaba en su oficina. Tomó el tubo de baquelita negra del teléfono y sintió el frío plástico en su oreja. Ese extraño material creado hacía poco más de un cuarto de siglo se difundía más y más, como gota de tinta en agua, por el mundo.

Sonó el teléfono en el amplio edificio al otro lado de la línea, dejando un eco que se perdía en el silencio.

 ”Uffff, ¿ahora quién llama? Tengo que concentrarme en el trabajo” pensó Juan frustrado atendiendo el teléfono:
 
─Asociación Argentina de Amigos de la Astronomía ¿quién es?

─Soy Ana Periódica, periodista del diario La Vanguardia. Me ha llegado el rumor proveniente de fuentes confidenciales, de que eventos inesperados muy importantes y de características astronómicas, están ocurriendo y entiendo que usted es el especialista en el tema. Quería saber si podría entrevistarlo.

Por la cabeza de Juan pasó una vez más la idea de llevar el nombre de su abuelo al conocimiento público y respondió:

─Hola, mucho gusto, sí, sería un honor y es también de suma importancia informar a la comunidad.

─Perfecto, ¿le parece si paso por el observatorio a las 16 horas?

─Por favor no me malinterprete pero si quiere, como parte de la entrevista, poder observar el fenómeno que descubrí, tendrá que ser en la noche.─Juan sabía que la propuesta podía ser considerada inadecuada, por eso aclaró ─Le doy mi palabra de caballero de que estará en un lugar seguro.

Ana dudó un instante. No era apropiado estar a altas horas con un desconocido, pero su curiosidad periodística era más fuerte.

─Muy bien ahí estaré y le tomo la palabra.

─Por favor, no tiene de qué preocuparse. La espero a las 19 hs para empezar la entrevista y cuando el sol se esconda podremos mirar con el telescopio.

─Hecho, lo veo por la tarde. Hasta Luego.

Ana se dirigió a su superior, Braulio Gómez, para pedir que algún caballero la acompañara a hacer la nota que había conseguido. No porque no supiera defenderse, sino que le parecía más decoroso no estar a solas de noche con un hombre. Sin embargo, Braulio argumentó ─¿Qué te va a hacer ese sabelotodo?, seguro que no se encuentra el pito ni con el telescopio─ Y largó una carcajada que fue secundada por todos los presentes. A Ana le parecía una falta de respeto siendo ella una dama. Ya había aprendido que discutir con su jefe era una pérdida de tiempo, pero no quiso dejar pasar la oportunidad de dejarlo en evidencia, así que le contestó:

─Parece que usted conoce muy bien las partes íntimas del astrónomo─. Todos en la oficina dejaron de reírse para pasar a un incómodo silencio que duró hasta que Ana levantó su mirada triunfante.

─Si no fueras la nieta de mi amigo...─ Farfulló Braulio dejando la oración en suspenso ─. No tengo gente, todos están ocupados, si querés la nota vas a tener que ir sola─. A Ana no le molestó la respuesta, de todas maneras, en su fuero íntimo no quería compañía.

Aún faltaban un par de horas para el encuentro con el Sr. Astrónomo. Como todavía seguía enojada por la situación con su jefe, decidió buscar a su amiga Helga para tomarse un café y desahogarse.

En aquel entonces el diario tenía sus oficinas en Avenida Rivadavia, entre Pasco y Rincón, y en la esquina se encontraba el famoso Café de los Angelitos, donde Ana y muchos otros de los trabajadores del diario y militantes del partido socialista, solían ir. Helga vivía a la vuelta, así que fue cuestión de minutos hasta que ambas estuvieron charlando en una mesa:

─Gracias por escucharme, Helga. No aguanto más a Braulio.

Helga sonrió señalándola con el índice.

─Vos solita quisiste ir a trabajar y no conseguirte un marido como hice yo. Estarías mucho mejor.

─Nunca, no necesito un hombre para sentirme realizada.

─Bueno, no te ofendas. Al final trato de ayudarte y me hacés sentir mal.

─Perdón, pero estoy contenta con mi elección y para charlar te tengo a vos, ¿acaso querés que te proponga matrimonio?─ Ana cerró la frase con una sonrisa para aliviar sus comentarios.

─No, por favor. Con Jorgito tengo suficiente─ completó Helga con humor.

Ambas soltaron una carcajada y siguieron su charla relajadamente por un par de horas más.

─Bueno Ani, querida. Te dejo que tengo que ir a preparar la cena─ dijo Helga, cerrando el encuentro─ Por favor vení a verme pronto así sé que estás bien después de la entrevista de hoy.

─No te preocupes, voy y te cuento todo. Gracias por escucharme.

Eran unas cuarenta cuadras al observatorio y a Ana le venía bien la caminata para despejarse. Tomó la avenida Rivadavia hasta la calle Billinghurst por la que fue para llegar a la Av. Diaz Velez que la llevaba directo a su destino.

En el centro geográfico de la ciudad de Buenos Aires se encontraba el Parque Centenario. Había comenzado a funcionar 35 años antes de que Ana llegara a las puertas del nuevo edificio, pronto a inaugurar, de la Asociación Argentina de Amigos de la Astronomía. El observatorio de la asociación estaba a tan sólo unos cientos de metros del sitio de construcción del Museo Nacional de Historia Natural que, aún en escombros, esperaba debutar como el Instituto Nacional de Investigación de las Ciencias Naturales y Museo de Ciencias Naturales Bernardino Rivadavia en los próximos años.
 
Las horas a Juan se le habían pasado como una estrella fugaz y a las 19:05 clavadas sonó el timbre del observatorio. Ana solía tener todo calculado. Si hubiera tocado el timbre en punto, habría parecido muy obsesiva; si lo hubiese hecho antes, parecería ansiosa; muy tarde quedaba poco profesional e irrespetuoso. Sólo cinco minutos daba el desinterés suficiente como para no sentirse a expensas del entrevistado.

Se escucharon unos pasos acercándose. Cada una de las retumbantes pisadas se perdían en un vacío infinito dando una sensación de que, tras las puertas del observatorio estaba el universo entero. La hoja de la puerta, a la derecha de Ana, se abrió rechinando unos diez centímetros y la parte superior del rostro de Juan asomó por la rendija. Miró a Ana precavido y abrió el resto de la puerta para dejarla pasar.

─Buenas tardes, soy Ana Periódica. ─ Se presentó sin avanzar.

─Buenas tardes, bienvenida. Pase por favor. ─ invitó Juan abriendo camino con su mano.

Ana entró erguida, con aires de seguridad y confianza. En la  mano derecha portaba una pequeña cartera de cuero con apliques de metal y en la izquierda llevaba anotador y lápiz. La obscuridad del ambiente le daba un aire tenebroso, aunque algunas hebras de las últimas luces del día entraban por las pequeñas ventanas. Ana caminó casi sin ver, en parte por la poca luz y en parte porque en su cabeza estudiaba las preguntas que le iba a hacer a su entrevistado. Salió de sus cavilaciones con el sórdido rechinar de una silla; se la ofrecía Juan con un gesto, para que se sentara. Ella se acomodó, alerta a cualquier movimiento sospechoso de aquel desconocido y esperó apretando con fuerza la manija de su bolso. Para sorpresa de Ana, Juan prendió una lámpara y muy amablemente la acercó para que la periodista pudiera ver. Con suma delicadeza acomodó unas tazas.

─¿Gusta un poco de té?.

─Si, por favor─ respondió Ana, un poco más relajada.

Luego de servir, Juan tomó asiento frente a ella y la miró fijo, queriendo dar la impresión de estar listo para responder a todas las preguntas. Pero al encontrarse con la mirada de su interlocutora quedó pasmado. “Que ojos más maravillosos, profundos como los misterios de la esfera celeste” Pensó Juan.

Al observarse fijamente sintieron que algo estaba bien, o mejor dicho, que algo se arreglaba. Como si alguna energía en el universo no estuviera fluyendo correctamente y al mirarse, se comenzara a enmendar. Pero, al serles imposible aceptar la falta de lógica de su sensación, o mejor dicho de su atracción, la dejaron pasar con vergüenza. La entrevista comenzó con un cambio de postura de Ana, disponiéndose a tomar nota y con Juan aclarándose la garganta.

─¿Cuál es el fenómeno que nos amenaza?─ Interrogó la periodista.

─Los resultados de mis investigaciones muestran un cambio en la órbita del planeta Venus. Por extraño que parezca, mis cálculos muestran que Venus se está acercando peligrosamente hacia nuestro planeta.

─¿Cómo es eso? No lo entiendo

Juan se detuvo un momento a pensar antes de responder ─Imagínese una boleadora siendo girada por usted. Si la suelta, con la fuerza que tiene por el giro, ésta sale disparada en una diagonal. Ahora imagínese a Venus girando alrededor del sol como la boleadora pero que se “suelta” y sale disparado hacia la órbita de la Tierra. Aunque más que soltarse pareciera como si algo lo atrajese, como si la bola de la boleadora fuera de hierro y apareciera un imán muy poderoso. Podría terminar en una colisión planetaria.

─¿Y cuáles serían las consecuencias de esta colisión?

─Sería catastrófico. El tamaño de Venus es casi el mismo que el de la Tierra. imagínese como si se chocara consigo misma. Provocaría el fin de la vida e incluso del planeta mismo─

─¿Está usted cien por ciento seguro de su descubrimiento y de todos sus cálculos?

Mientras Ana hacía esta pregunta, le temblaban las piernas, pero extrañamente el miedo se esfumaba al escuchar las respuestas de su entrevistado.

─Al principio pensé que era un error, entiendo lo descabellado de mi afirmación, revisé las cuentas veinte veces antes de consultar con mis colegas de mayor confianza y todos coincidimos en que los resultados son correctos. Al dar aviso al resto de la comunidad de astrónomos, las predicciones se fueron confirmando. Lamentablemente es un hecho atroz pero real.

─¿Pero, no tenemos ninguna opción, acaso es el fin y nada más?, ¿están al tanto las autoridades nacionales?

Juan quedó en silencio, Ana notó miedo en su mirada pero aguardó paciente la respuesta. Juan tomó aire y comenzó a hablar ─Desde la toma del poder del Grupo de Oficiales Unidos y a través del presidente, Edelmiro Farrell, las fuerzas de seguridad mostraron acciones y actitudes terroristas hacia las Universidades Nacionales. Si bien el mensaje está corriendo por la comunidad internacional de astrónomos, temo por mi vida en este país. De todos modos, no hay mucho que se pueda hacer a menos que construyan máquinas similares a las que Julio Verne describió en su libro “De la Tierra a la Luna”, como el cañón Columbiad capaz de lanzar un proyectil a la Luna.─ Terminó la frase apretando los labios y tragando saliva.

Ana se percató de estos gestos e involuntariamente lo imitó. No podía creer lo que escuchaba pero juntó coraje y continuó la entrevista por un largo rato hasta que Juan, al ver la hora, tomó las riendas.

─Ya es hora de subir, este es el mejor momento para observar a Venus. Puedo mostrarle el telescopio con el que hice el descubrimiento.

─Sería un placer, aunque me cuesta salir del shock.

Juan ofreció su mano con la palma expuesta como pidiendo permiso para tomar la de Ana. La periodista aceptó. Con suavidad y firmeza la guió por los oscuros recovecos del observatorio hasta llegar al telescopio principal. Mientras caminaban, ella se dejaba llevar, no sabía por qué pero confiaba en aquel extraño, su corazón le decía que estaba bien estar con él, se sentía cómoda, segura, contenida y llamativamente feliz, inclusive luego de haber escuchado la terrible noticia.

El interior de la cúpula que contenía al telescopio era majestuosa. En el centro de la sala se elevaba una plataforma octogonal terminada en el más fino pino blanco, a la cual se accedía por dos escaleras laterales. En el medio de este escenario había una mesa, octogonal también, que sostenía al gran telescopio Gautier. Juan había ubicado a un costado un pequeño escritorio con su cuaderno de notas, lápices y otros artículos de librería; y en un rincón el infaltable telescopio de madera que le había regalado su abuelo. Nunca se sentaba a observar sin la compañía e inspiración de aquel catalejo estelar, invaluable para él.

Juan le indicó a su invitada que aguardara mientras ajustaba el equipo principal, ella se posó sobre el escritorio y el astrónomo comenzó los preparativos. Se acercó al telescopio de metal pintado de rojo para llevar su ojo al ocular dorado. Los primeros segundos pasaron y Juan seguía concentrado en su tarea. Comenzaron a correr los minutos y Ana se impacientó:

 ─¿Hay algún problema?─ preguntó ansiosa.
 
Juan salió de su trance y respondió con tono confundido:

─Algo raro está pasando, parece que la trayectoria cambió, como si volviera a su lugar original. Por favor, venga más tarde que tengo que ver qué está pasando.

Sin titubear Ana respondió:

─Mi trabajo es informar, yo de acá no me muevo.

Juan le dirigió una mirada preocupada pero, al volver a encontrar sus ojos color almendra, sintió una paz que le borró todo miedo.

─Está bien, quédese, pero por favor guarde silencio mientras tanto─ respondió nervioso.

Ana asintió con un gesto como si cerrase sus labios con un cierre. Juan tomó su cuaderno de notas y empezó a revisarlo, miraba una y otra vez el ocular y el cuaderno ajustando diferentes perillas y haciendo anotaciones de tanto en tanto.

─Disculpe mis modales─ dijo Juan unos instantes más tarde ─agradezco su compañía─ dejó una pausa y preguntó ─¿cómo es que usted se enteró de mi descubrimiento?

Ana sonrió orgullosa y contestó ─me asignaron seguir la historia de la construcción del nuevo observatorio, hacía ya un tiempo que venía merodeando debo confesar. Me sorprendió que hace un par de días llegaron varias cartas internacionales con carácter de urgencia y…

Juan resopló una sonrisa y terminó la frase ─era usted quien forzaba la tapa del buzón; la perdono porque fue por una buena causa y porque está siendo honesta ahora─.

Había notado que revisaban sus cartas pero creyó que eran las autoridades militares, en el fondo se sentía aliviado de que era Ana quien lo espiaba.

Algo que había ayudado a Ana en su oficio era el ser entrometida, si es que la situación lo ameritaba. Pero lo que siempre la había acompañado en su carrera, era su instinto; que en ese momento le gritaba que se tenía que quedar.

Horas más tarde, Juan continuaba trabajando incansablemente, perdido en su investigación. Mientras, Ana escribía el primer borrador de su nota cuando repentinamente escuchó un ruido y sin sobresaltarse preguntó indiferente:

─¿Hay alguien más acá?─

Juan la miró extrañado y distraído.

─Perdón, no quería interrumpirlo─ le respondió leyendo el gesto.

─No, no hay nadie más en este momento, ¿por qué lo pregunta?─ preguntó Juan sin prestar mucha atención.

─Por nada.

Ana miró sobre su hombro tratando de revisar el lugar con disimulo, caminó en silencio con un gesto distraído haciendo que estiraba el cuerpo, pero observando todo con vista de halcón, su intuición le decía que algo andaba mal. Entonces lo notó, uno de los pobres haces de luz de las lámparas que alumbraban el lugar se reflejó sobre el cañón de un revólver Webley que asomaba entre las sombras, apuntado en dirección a Juan.

El arma pertenecía a Roberto Inindulgente. Un tipo rudo; criado con valores simples, claros y sin bemoles. Hijo de militares aristócratas, seguía sin cuestionamientos al gobierno imperante. Hacía tres días se le había asignado la misión de asesinar a Juan Astrónomo. Toda la explicación que había recibido era que el científico había descubierto una amenaza mundial y, si lograba divulgarla, generaría un pánico global que sería peor que la propia catástrofe que anunciaba; además de atraer la atención internacional a Argentina en plena dictadura militar, pero eso no requería ser informado. De haberse hecho, le hubiera dado a Roberto una motivación extra.

Desesperada pero con suma precisión, Ana lanzó su bolso, con los apliques de metal al frente, estimando la trayectoria hacia donde debería estar la cabeza del agresor misterioso. Una secuencia de sonidos estridentes se sucedió en escala: primero se escuchó la manija del bolso sobre el cráneo de Roberto, acompañado de un grito de dolor, seguido de un disparo desviado, un grito de pánico de Juan y un alarido de festejo de Ana.

Para Roberto el rol de la mujer era muy claro, debía quedarse en casa, realizar sus quehaceres domésticos y estar fuera de los asuntos de los hombres. Fue por esto que encaró furioso a la rescatadora; no se dignó a usar el arma, un disparo seco no iba a enseñar la lección que quería imponer. Guardó el revólver en su espalda entre el cinturón y el cuerpo y preparó sus puños con ira y una sonrisa sádica. Pero gracias a la  distracción misógina, Juan aprovechó la oportunidad y golpeó con todas sus fuerzas la nuca del atacante, usando la herramienta que mejor conocía: el telescopio de madera que le había regalado su abuelo. Roberto cayó inconsciente.

Sin perder más tiempo, la aguerrida periodista tomó con la mano izquierda su anotador y con la derecha al astrónomo que llegó a agarrar su cuaderno antes de escapar a toda prisa del observatorio. Salieron en plena madrugada y atravesaron el Parque Centenario bajo las luces del alumbrado público.

El parque es como un gran círculo verde en el medio del mapa. Corrieron por la avenida Díaz Vélez, siguiendo la tangente, hasta que sus pulmones no resistieron más. Se detuvieron a unos metros de la esquina de la calle Medrano, jadeando como perros y vigilando la retaguardia.

Habiendo recuperado el aliento, Ana recordó el subte A. La estación Castro Barros estaba a unas pocas cuadras. Esa podía ser una vía de escape segura y rápida, el único problema era que todavía no abría sus puertas, ya que seguía siendo de madrugada. Corrieron igual por Medrano en busca de nuevas ideas, llegaron finalmente a la esquina que buscaban y doblaron por Rivadavia. Tal como esperaban, estaba cerrada.

Pese al peligro inminente que parecía acecharlos, la cara de Juan no reflejaba preocupación por ser perseguido sino que se veía perdido en sus cavilaciones astronómicas.

─¿Qué hacemos ahora?─ preguntó Ana.

─Ver por qué Venus está comportándose tan extraño.

Ana se enfureció. Amenazados de muerte por un maniático desconocido y él perdido en las estrellas, fue el límite de su paciencia. Se acercó con ímpetu para despabilar a su entrevistado. Juan la tomó por la cintura antes de que pudiera hablar siquiera. Sus ojos, solo separados por sus narices, se miraron tan enojados como apasionados.

─Agradezco su osadía, me ha salvado usted la vida y estaré eternamente en deuda. Pero este altercado no corre por su cuenta y debe usted alejarse antes de que termine lastimada. Por mi parte necesito resolver qué está pasando con los planetas.

─No voy a ningún lado, me quedo a donde esta historia va─ contestó Ana sin resistirse al agarre de Juan.

Treinta años antes, detrás de donde ellos estaban, se había inaugurado la confitería “Las Violetas” que hacía tan sólo unos minutos atrás había empezado a servir café. Juan pensó rápido. Dejó ir la cintura de Ana, tomó su mano con determinación y caminó acelerado, vigilando en todas direcciones y llevándola hacia la puerta de la confitería. El astrónomo se dio cuenta que era un lugar público donde había movimiento desde temprano y varias personas como potenciales testigos. No había un plan más seguro que ese: esperar en la confitería hasta que el subte abriera y así poder alejarse y ganar tiempo.

Se acomodaron en una mesa de madera cuadrada con dos sillas opuestas. La confitería tenía una gran barra que se orientaba hacia enormes ventanales que miraban a la calle; en lo alto el techo, con sus bellas lámparas y refinadas terminaciones, era sostenido por majestuosas columnas. Un lugar a la par de los mejores cafés de Europa.

Juan realizó dos rápidas señas: primero formó una “V” con los dedos índice y mayor, luego con el índice nuevamente y el pulgar representó la “C” como sosteniendo una pequeña taza entre los dedos. De esta forma indicó al mozo que le sirviera un par de cortados. Luego pidió a Ana silencio con el índice extendido sobre sus labios, necesitaba analizar sus anotaciones. Antes de iniciar le indicó que se mantuviera vigilante mientras él interpretaba sus notas. Durante unos veinte minutos la periodista mantuvo la calma, pero llegó un punto donde no pudo contenerse más.

─¿Qué está pasando? ¿Por qué está revisando tanto sus notas? ¿Quién era esa persona que intentó dispararle?

Juan tomó aire, entendió que estaba asustada y contestó con calma:

─Lo que vi anoche es que Venus está volviendo a su lugar, pero no tuve tiempo de  registrar y hacer los cálculos y observaciones necesarias para saber qué podría ocurrir. En cuanto al agresor, verdaderamente desconozco quién es y sus motivos, yo debería estar pensando en cruzar el charco para zafar ─le salió finalmente su bronca en claro lunfardo─ pero me preocupa más qué está pasando en nuestro sistema solar y si hay alguna novedad en cuanto al destino de nuestro planeta.

─¿Y cómo va a completar sus notas sin un telescopio?

Juan se apretó el entrecejo con el dedo índice y el mayor, como si eso le ayudase a pensar mejor. Respiró profundo, exhaló por la boca como si estuviera rindiéndose y entonces elevó su cabeza. Sus ojos brillaron, relajó el ceño y exclamó:

─El San José, el padre Taillefer tiene un telescopio. ¡Vamos rápido!

─¡De qué está hablando!, basta de sin sentidos, explíqueme qué pasa. No vamos a ninguna parte hasta que no me diga qué carajo pensó─ dijo Ana olvidando todos los modales.

─A unas estaciones de subte está el Colegio San José. El padre Taillefer, encargado del lugar, me había pedido ayuda para hacer unos ajustes en el observatorio. Podemos ir ahí para terminar mis observaciones. Déjeme revisar mis notas hasta que abra el subte y nos vamos derechito para allá. Ana asintió con la cabeza y volvió a su mirada vigilante.

Se tomaron cada uno el café en silencio. Juan mirando fijo sus notas,  Ana tomando apuntes para la noticia en su anotador. Habían pasado tantas cosas en las últimas horas que por un momento no supo quién era, qué hacía, porqué estaba ahí. Recién en ese momento se dio cuenta de que había olvidado su bolso en el observatorio.

El sol salió completamente, se sentía su calor a través de la ventana del Café. Cada uno resguardó sus notas mirando alrededor en busca de alguna figura sospechosa. Nada les llamó la atención, así que se levantaron disimulando estar tranquilos y se fueron para la estación.

Roberto despertó del desmayo, le dolía la cabeza y al tocarse le quedó un poco de sangre en los dedos. Se limpió con su pañuelo, que guardaba prolijamente doblado en el bolsillo posterior de su pantalón y fue tras la víctima que tenía encomendada. Al salir del observatorio el sol estaba brillando. Roberto era un experto rastreador y con toda calma retomó la cacería. Observó la situación, su entrenamiento era vasto y podía deducir con gran precisión que decisiones podían llegar a tomar las presas que perseguía. Pero comenzó por la evidencia más obvia: el bolso que la atrevida había lanzado.

Ana y Juan esperaban ansiosos la llegada del subterráneo en el andén. Sin pensarlo se tomaron de las manos. Se preguntaban si hubiera sido mejor ir caminando, se preguntaban por qué alguien podía querer matar a Juan y cada uno a su manera se preguntaba porqué el sistema solar se había vuelto loco. Perdidos en pensamientos diversos, el tiempo pasó desapercibido y el ruido rechinante de los frenos del subte y su olor característico los trajo de nuevo al presente. Las puertas se abrieron y entraron rápidamente mirando en todas direcciones, lo cierto es que con el susto y con la prisa nunca habían visto al agresor, así que podía ser cualquiera. Las Brujas, como llamaban a los vagones construidos en la ciudad Belga del mismo nombre, comenzaron su recorrido que, si bien corto, a Ana y a Juan les pareció una eternidad. No se soltaron de las manos ni por un segundo.

Llegaron a la estación Loria y miraron furtivamente a cada persona que entraba a su vagón. Siguieron hasta Plaza Miserere con el mismo miedo y finalmente bajaron en Alberti, queriendo volver a la superficie donde se sentían menos sofocados y con más posibilidades de escapatoria.

Caminaron una cuadra, en dirección al norte, por la calle Larrea, y a su derecha, imponente, se erigía el colegio San José. Su muralla en la intersección con la calle Bartolomé Mitre cortaba en una ochava de tres pisos y continuando el muro por esta última calle, enormes ventanales se veían separados por macizas columnas. Se dirigieron a la puerta principal donde Juan golpeó ansioso. Un joven monaguillo abrió la puerta, tenía aspecto preocupado, seguramente por la ansiedad del llamado de Juan, pero no había tiempo para disculpas. ─¿Dónde está el padre Taillefer?─ preguntó Juan con prisa: ─es una emergencia─. El confundido monaguillo los guió hasta la oficina del padre, que por suerte desde muy temprano ya estaba trabajando.

Con educación, Juan comenzó por presentar a su acompañante y durante unos veinte minutos explicó la situación al padre mientras Ana aguardaba sentada a su lado. Taillefer escuchó con paciencia y atención. Se mostró empático en todo sentido y desde el profundo respeto científico que tenía por aquel astrónomo, les dio permiso para utilizar las instalaciones e inclusive refugiarse del agresor misterioso.

Ana y Juan subieron rápidamente a la torre del observatorio, Juan miraba los escalones y sus notas alternadamente mientras Ana lo agarraba del brazo cuando se estaba por tropezar. Extrañamente tenían una dinámica juntos tan fluida que parecía que se conocieran de otra vida.

Una vez que estuvo cómodo, el astrónomo quedó absorto en su trabajo haciendo y repitiendo sus cálculos. Ana decidió avanzar en el borrador de su artículo. Sin embargo, le resultaba muy difícil concentrarse porque Juan no paraba de murmurar. Superada finalmente por la situación le preguntó irritada:

 ─¿Qué es lo que pasa?─. Juan carraspeó preocupado y respondió con un tono dudoso, por no tener acceso a las observaciones a través de un telescopio ─Mis estimaciones predicen que Venus estaría volviendo a su órbita original hacia la noche, pareciera como que todo retorna a la normalidad pero hasta que no llegue el atardecer de nuevo no voy a poder confirmar mis cálculos.
 
Ana quedó boquiabierta, “todo esto para nada” pensó. No sabía si alegrarse porque no iba a destruirse la Tierra o entristecerse porque no iba a poder publicar una historia maravillosa. Pensó un momento, no podía creerlo, se planteó que algo debía estar mal y preguntó ofuscada:

 ─¿Está seguro? ¿Cómo puede ser?─ Juan levantó los hombros en un gesto de desconocimiento, ─así de simple es lo último que observé en la Asociación Amigos de la Astronomía, no puedo encontrar una explicación todavía─ respondió, rendido ante su ignorancia.
 
Ana pensó un momento, necesitaba reorganizarse.

─Mire, no vivo lejos de acá─ le dijo Ana escribiendo su dirección con un lápiz en un papel viejo que tomó de una de las mesas del observatorio─ Voy a casa a acomodarme las ideas porque ahora no sé qué escribir. Cuando haya terminado con sus observaciones y cálculos por favor páseme a buscar y terminamos esta historia─ ordenó Ana.

─Pero el asesino anda suelto por ahí, es muy peligroso─ inquirió Juan.

Ana respondió confiada y envalentonada:

 ─Sé cuidarme muy bien, si no fuera por mí, usted estaría muerto. Me quedo tranquila de que está seguro acá en el colegio─ terminó su frase golpeando con el lápiz la mesa a través del papel para poner un punto final y así darle énfasis a su afirmación antes de irse.
 
Una vez en su casa, Ana sintió un gélido escalofrío pasando por su espalda. “¿Y si Juan no la pasa a buscar porque el asesino ese lo había encontrado?” pensó la periodista aterrada. “Nunca debí haberlo dejado”; se repetía una y otra vez. Pero al recordar la mirada del astrónomo le volvió la paz al cuerpo.

Pocos tenían la experiencia de Juan. Había aprendido astronomía con su abuelo, como oficio antes que como catedrático. Confiaba en sus observaciones sin lugar a duda, lo que no quitaba que investigara profesionalmente hasta que sus interpretaciones tuvieran sentido. Por eso quedó anonadado cuando se encontró al atardecer con que Venus volvía a alejarse de la órbita. Se dejó caer sobre una vieja silla de madera.

El padre Taillefer había pedido dejar en el observatorio una jarra con agua y un par de vasos para los refugiados. Juan tomó un poco y se mojó la cara echándose unas gotas con los dedos, como si eso fuera a despertarlo; tal vez, toda esta locura era sólo un sueño, al final de cuentas hacia 48 hs que no dormía. Decidió descansar un poco. Bajó de la torre y pidió al monaguillo si podían ofrecerle algún lugar donde recostarse. Juan se sentía afiebrado pero eran sólo los nervios de estar desconcertado; en parte por lo bizarro de la situación astronómica y en parte porque no podía sacarse el olor a gardenia y la mirada implacable de Ana de la cabeza.

Despertó de su siesta en el sillón de la sala de maestros, desorientado. Era de madrugada. Poco a poco fue recordando todos los hechos: el agresor, sus cálculos incompletos, la pérdida del telescopio de su abuelo y el hecho de que sus últimas observaciones en la torre las había hecho sin este, sin su cábala. De entre toda esa confusión Ana apareció en su mente, como un maravilloso amanecer después de una larga noche. Este último recuerdo lo animó a levantarse. Pasó por el baño y se lavó la cara esperando que esto lo despabile, se miró a los ojos en el espejo y pensó en voz alta:

─Sé que los cálculos están bien, desde un primer momento el hecho de que un planeta cambie su órbita ya no tiene sentido así que el que retorne a ésta tampoco agrega mucho. ¿Qué pasa entonces?─ una idea apareció de la nada, que si bien absurda era lo más cuerdo en toda esta locura. Volvió desesperado al observatorio del colegio, tomó su cuaderno de notas y se fue corriendo, agradeció al padre Taillefer y salió a la calle en plena madrugada.

Cuando llegó a su casa Ana se dio un baño para despejarse, dejando que las ideas cayeran solas, pero sólo podía pensar en una cosa o más bien en una persona: Juan. Al bajar el sol prendió una vela para iluminarse, en todo sentido. Recapituló la historia en su memoria y la pasó al papel. Para cuando terminó, había tirado a la basura varios borradores. Estaba envuelta en su bata y con una toalla a modo de turbante en la cabeza. Se sentía frustrada, pero no por no tener el final de la historia para su nota sino porque, a pesar de que ella creía que el astrónomo era un pedante, sentía algo por él, y no lo admitía.

Ana había tomado el oficio del periodismo de su abuelo, desde chica escribía todo lo que veía en un cuaderno que su querido mentor le había regalado al empezar la escuela primaria. Al principio fueron dibujos con unas pocas letras; luego, con el pasar de los años se fueron haciendo notas más y más elaboradas. En ese cuaderno fue creciendo su pasión y dedicación al periodismo. Sus padres no aprobaban esta profesión, pero su abuelo siempre estaba ahí para escuchar, corregir y hasta publicar los artículos que Ana escribía. Su motivación no sólo era por el amor a la profesión sino también tener la excusa de sentarse junto a su guía a leer historias. En quinto grado se había subido a lo más alto del árbol de moras del patio para alcanzar la ventana de la sala de profesores de la escuela y desenmascarar a la directora que se robaba plata de las carteras de las maestras. En la escuela secundaria, su curiosidad y determinación le construyeron una mala fama. Había estudiado en la Facultad de Periodismo de La Plata, que desde 1934 impartía clases en pos de la defensa de la libertad de expresión. Era de las pocas mujeres que asistía a la universidad por esos tiempos y lo hizo a costa de dedicarse ciento por ciento a eso, su pasión. Constantemente era incomprendida por los demás, pero cada artículo llegaba a los lectores que tenían que llegar. Esta era la primera vez que no tenía una noticia clara y culpaba de esto a Juan para no hacerse cargo de su propia frustración.

Ana vivía en la casa de su familia, pero en una dependencia con una entrada separada que oficiaba de un pequeño departamento. La relación con sus padres nunca había sido amena y tener esa privacidad y autonomía era lo más conveniente para todos. Este pequeño departamento era apenas un ambiente con la cama al pie de la única ventana; una salamandra que la abrigaba y donde cocinaba; una cortina que separaba del resto de la habitación la bañadera, el inodoro, una mesa con una palangana y la jarra para el agua. Opuesta a la ventana estaba la puerta, que  alguien golpeó tres veces con fuerza. Ana quiso suponer que era Juan, pero inmediatamente se acordó que había perdido su bolso al usarlo como arma y que al hacerlo dejó una pista al agresor ─¿sería él que la buscaba para llegar a Juan?. El retumbar del tercer golpe se continuó con la voz de Juan avisando de su llegada. Ana respiró aliviada. No le importó que llegara en medio de la madrugada, quiso correr a abrir pero su vanidad la detuvo. Se dio unos instantes para sacarse el toallon de la cabeza y acomodar el pelo mojado con los dedos.

─Ya voy─ dijo para ganar un momento más, respirar profundo y aceptar que su instinto no había fallado y que sabía que él había estado siempre en camino y nada malo le había pasado.

Abrió lo más despacio que pudo y sus miradas se encontraron. El notó la bata al ver su hombro y bajó la mirada en un gesto de respeto a la intimidad de aquella dama ─puedo esperar a que se vista─ dijo nervioso. ─Un momento nomás─ le respondió agradecida y cerró la puerta. Al verse ambos habían aceptado sus sentimientos sin dejar espacio a las preocupaciones que los acechaban. Ana se vistió rápidamente con un vestido sencillo de verano que le había regalado el difunto abuelo. Cuando abrió la puerta nuevamente sólo se miraron y como dos polos opuestos se atrajeron violentamente el uno al otro en un apasionado beso. Su unión amalgamaba el amor más puro y misterioso, capaz de mover planetas. Si no eran ellos los que canalizaban esa atracción entonces sería el radiante cuerpo planetario el encargado de hacerlo. Ambos sabían que en esa unión, todo volvía a su lugar y no había nada de qué preocuparse.

Tras el beso Ana preguntó ─¿Y el fin de nuestro mundo?─ Juan le contestó ─Mi mundo es usted.

Poco a poco en todo el globo los astrónomos que habían sido avisados empezaron a quedar anonadados ante la sorpresa de que el brillante planeta estaba volviendo a su lugar, sin poder dar explicación de por qué se había salido de su órbita ni de por qué estaba volviendo a la misma. Estas noticias no tardaron en llegar tampoco a las altas esferas de la milicia dictante, de donde inmediatamente se ordenó avisar al brigadier Inindulgente para que detuviera su misión con un simple llamado.

Roberto era un hombre leal pero aún más era orgulloso. El odio que había acumulado contra aquella periodista entrometida lo llevó a cambiar, en lugar de anular, la orden de no asesinar. Obedecería en principio, la orden de no matar a Juan, pero nadie le había dicho que no matara a Ana.

Su primer instinto fue ir a la casa de aquella maldita. Tenía la dirección gracias a el documento de identidad que había encontrado dentro del bolso de Ana. y se dirigió a su destino sin titubear. Tenía el arma preparada y esta vez no fallaría, se aseguraría su victoria matándola.

El deseo mutuo de Juan y Ana los hizo olvidarse de sus preocupaciones. La falta de lógica en los cálculos astronómicos se transformó en caricias espaciales, la falta de inspiración para escribir la nota se tornó respiración acelerada y finalmente el anhelo de ser idolatrados por sus respectivos abuelos se convirtió en alegría al darse cuenta de que hubieran estado felices por saber que sus nietos encontraron el amor.

La pasión que despertó la unión de Ana y Juan resonó también en el resto del sistema solar. Era tal el balance que requería el universo de su unión, que su separación había cambiado la órbita de Venus. Pero no como castigo sino como llamado a que sus espíritus se encontraran y se unieran. Aún más extraño fue lo poco que incidió todo el movimiento planetario, ya que la única evidencia de esto eran las observaciones en el telescopio pero ningún otro acontecimiento se derivó como consecuencia del cambio de órbita. Los profesionales no podían encontrar explicación a tales fenómenos pero cada evidencia confirmaba los desplazamientos del planeta. Sólo un pequeño evento tuvo una consecuencia mortal. Una suave brisa estelar llegó apenas a empujar una maceta que Doña Ramona había dejado descuidadamente mal apoyada en el borde de su balcón, con suerte tal que cayó en la dura cabeza de un desafortunado transeúnte. Esta persona murió instantáneamente, sus deseos, sus anhelos, sus miedos y sus pecados se fueron en un momento, tan sólo unos segundos y ya nada existía, ni siquiera la sed de venganza por su víctima, aquella maldita que había evitado que concretara su misión. Sólo encontraron junto a él, un bolso de cuero con apliques de metal entre sus manos, que no fue suficiente para identificarlo. Por su parte, los espíritus individuales de Juan y Ana en su apasionado encuentro dejaron de ser dos para fusionarse en uno: JuAna.
