---
title: "DiAna"
---

<!-- :::{.derecha} -->
<!-- ```      -->
<!-- A la escultora de libros, -->
<!-- que en estos tiempos de 0 y 1 -->
<!-- su arte mantiene viva estas páginas. -->

<!-- -Sergio Sclovich- -->
<!-- ```      -->
<!-- ::: -->

Juan Palindromemordnilap es un robot sencillo. Sus funciones son simples y claras: ser un albañil que construye y arregla todo tipo de estructura edilicia. Tiene una rutina ordenada; desconecta su cargador temprano en la mañana después de una noche de recarga, toma sus herramientas que deja previamente organizadas con prolijidad y recibe la orden de a dónde tiene que ir a construir o reparar algún edificio.

La mañana del martes 1^ero^ de Junio del 2999 sale a realizar un arreglo en el piso 51, una pared que se había roto debido a la entrada de humedad. Se dirige a la estación del transporte público más adecuado para llegar a su destino y espera. Mientras tanto, revisa los planos de la obra que va a reparar para aprovechar el tiempo.

Baja en la parada correspondiente y se coloca sobre la vereda transportadora. Como robot reparador está programado para detectar fallas, arreglarlas o reportarlas. Entonces, al ver a Ana Gramarg acercarse por la vereda transportadora contraria, queda desconcertado. En un instante, detecta múltiples señales de inestabilidad en el emulador emocional de la robot que ve por delante.

Dicho emulador emocional consiste en un núcleo del cerebro robótico especialmente diseñado para dar respuestas emotivas a sus interlocutores humanos. Al principio exclusivamente a éstos, pero tras un estudio de la Asociación para Robotización de la Sociedad (ARS) se mostró que ver dos robots interactuar como personas, era menos estresante para los humanos. Así que las respuestas emocionales se extendieron a todos y todo.

Las fallas que detecta Juan en el emulador emocional de aquella robot son poco convencionales, lo que le genera dificultades para establecer un diagnóstico a reportar. La demora en la definición del problema es suficiente para distraer a Juan por un instante, quien sorpresivamente siente que se desbalancea y se tropieza tras haber chocado con algo o alguien.

Desde el suelo, Juan mira a su alrededor volviendo a recalcular su posición. En la evaluación de posibles daños, se encuentra con que la causa de su desbalance es esa misma robot defectuosa. Cuando la enfoca tras el choque, nota que ella está hablándole en un tono que denota enojo. Su respuesta es la indiferencia. Deja que la robot se aleje, concluye que su sistema no es capaz de diagnosticar la falla y se deja llevar por la cinta transportadora, incorporándose.

A continuación escucha el quiebre de la plataforma a sus espaldas y ve a Ana caer. Dada su programación para evaluar diferentes estructuras, calcula la probabilidad de supervivencia de aquella robot que cae y compara esta probabilidad contra el riesgo propio de ir a socorrerla. Estima que ayudar a Ana tiene menos posibilidades de dañarlo a él que lo que se dañaría ella si no la ayuda. Siguiendo la lógica, corre el riesgo de lanzarse a rescatarla. Tira sus herramientas al piso, avanza rápidamente unos diez metros y salta al vacío con la cabeza al frente. Adopta la postura más aerodinámica que su cuerpo le permite y toma velocidad en la caída. Sus sensores perciben el viento escurrirse entre ellos cada vez más fuerte hasta que finalmente la alcanza. La toma entre sus brazos y aprovecha el momento del impacto para dar un giro en el aire de forma que sus pies quedan listos para frenar la caída. Aterriza abruptamente sobre la plataforma transportadora más cercana, que resulta ser la del piso 41, generando un gran estruendo. Sus fuertes piernas preparadas para levantar y sostener paredes, contienen el impacto sin mayor problema. Con el cuidado con el que construye estructuras, apoya a Ana a salvo en la plataforma.

El programador de Juan había sido Jeremías Wyatt. Obsesivo y detallista como él sólo, programó su robot para ser sumamente cuidadoso. Tenía centros de control individuales que le permitían evaluar en detalle cada una de sus acciones.

Mientras Juan recuesta a Ana, su programa de memoria devuelve imágenes del cuidado con el que Jeremías lo había construído, como el que él mismo emplea en cada tarea de albañilería que le es asignada.

Tras hacer una verificación de los daños, que fue mínima como lo había predicho, registra que Ana le habla:

 ─¿Por qué me salvaste?
 
La pregunta le parece extraña, ¿por qué un robot no habría de saber la respuesta?, piensa Juan. Debería haber calculado las mismas probabilidades que él. De haber sido humano, probablemente hubiese contestado con vehementes palabras producto de los intensos sentimientos que experimentan, pero como no lo era, fue capaz de atenerse al sistema de ética y respeto, de modo que sólo contestó:

 ─Porque, dadas las cualidades con las que fui construido, la probabilidad de salvarte era del 85%. No se justificaba dejar que te destruyeras─.
 
La robot Ana se levanta tambaleante y se aleja. Juan sigue detectando fallas en su emulador emocional, de hecho aún más graves que antes. pero como no puede clasificarlas no las reporta y la deja ir. Sin embargo, por algún motivo no la borra de su memoria.

Juan reporta el incidente de la ruptura de la plataforma y sigue su camino. Sube al piso 51 y se dirige a reparar lo que le fue encomendado. Una vez en su casa, deja las herramientas prolijamente ordenadas y se conecta a recargar su batería como todas las noches. El recuerdo de Ana no lo abandona.

Normalmente el sistema operativo de Juan se pone en un modo de mínimo uso de recursos durante la carga de su batería. Sin embargo, esa noche un pequeño pero poderoso programa sigue funcionando, buscando incansablemente el diagnóstico del emulador emocional de aquella robot que salvó. A la mañana siguiente, habiendo llegado la hora de ir a realizar un nuevo arreglo, sale de su modo de mínimo uso descubriendo que, a diferencia de cualquier otra mañana, su batería no está completamente cargada. Debido a la intensa búsqueda de información e interpretación de la falla que detectó y ante la imposibilidad de sacar esa pregunta de su sistema, nunca estuvo verdaderamente en modo de mínimo uso y, no pudiendo recuperar la energía faltante, sale a trabajar de todas formas.

Durante el día se ve obligado a enlentecer sus tareas, ya que el resto en su batería no es suficiente para todo lo que normalmente hubiera hecho. Con lo último disponible logra llegar a su casa nuevamente y conectarse. Durante seis meses sigue trabajando de la misma manera, diagnosticando, día tras día una falla en su batería; lo que indica una reposición. Pero decide determinar el origen de la falla que provoca la situación de carga parcial antes de cambiarla por una nueva. Finalmente, al borde del colapso energético, reevalúa su estado. Concluye que el problema es la robot. Si no logra diagnosticarla, él mismo terminará dañado.

A la mañana siguiente se encuentra con su batería completamente cargada. Comienza el día enviando un formulario 7228-B4 pidiendo 24 horas de licencia de trabajo para arreglos autoaplicados. Si un robot tiene pequeñas refacciones que realizar y sus habilidades están homologadas dentro del reglamento, se le otorga este tiempo sin exigir mayores explicaciones.

Empieza por buscar información de la robot. Aprende que, además de que está identificada con el código 272727, es una robot escritora muy exitosa de los últimos años.

Si Juan fuese humano, se podría haber preguntado por qué una robot llegaba a ser exitosa, especialmente en un área creativa. Más aún, se podría haber preguntado por qué existen robots masculinos y femeninos. Si Juan hubiera sido humano y hubiera buscado esas respuestas, se habría encontrado con que la razón de por qué había robots de géneros distintos era que en el año 2940 la ARS había develado un estudio que mostraba que los humanos se estresan menos tratando con robots heteronormativos. Sin embargo, la verdadera razón era que la implementación de robots de sexos separados resultó dar muchas ganancias en el mercado ilegal; que aún, según las reglas de ese entonces, lo era. El uso de robots para la prostitución en todos los formatos imaginados, era un gran negocio. Al poco tiempo de ver el potencial económico de una institución como la ARS, la corrupción no tardó en sumarse al juego.

En cuanto al éxito de los robots en un área creativa como la escritura, bajo la excusa de subir la autoestima pero con la intención de mantenerla baja, la ARS propuso una categorización de la literatura. Argumentaban que esto permitía que los robots tuvieran un atractivo como escritores y que esto motivaría a los *Homo sapiens* a leer más y por tanto estar mejor educados y de esa forma poner la tecnología al servicio de una mejor calidad de vida. Si Juan hubiera sido humano, podría haber sospechado que usaron a todas las áreas artísticas, pero espacialmente a la literatura, para instaurar ideas y adoctrinar a la ciudadanía servil a conveniencia de los *Homo utrasapiens*.

Pero Juan no es humano y no se hace ningún cuestionamiento. Recopila todos los escritos de Ana y los lee en unos pocos minutos. Revisa los planos técnicos de la robot, y no encuentra ningún error, salvo por una porción de código de programación que le resulta atípica. Esta porción de código no se muestra como una equivocación, apenas despierta un mensaje de advertencia imperceptible que no lleva a detener ni alarmar a ningún otro programa ni circuito. Pero, una vez en funcionamiento genera comportamientos completamente incoherentes para la lógica de un robot.

Estas incoherencias se basan en optar por ciertas decisiones que no necesariamente son las más favorables para su propio bienestar ni una ayuda concreta a otros. Más bien, este extraño código otorga un cierto tipo de satisfacción, concepto inimaginado para un robot, donde la respuesta es estar feliz y disfrutar de la compañía de alguien.

Frente a esta anomalía, Juan decide indagar sobre la máquina que lo tuvo en vilo tanto tiempo accediendo a la base de datos común, lo que antiguamente se conocía como internet, pero que ahora era una red sumamente controlada. Las tecnologías habilitadas para la programación de robots sin intervención humana eran muy modernas y solo los últimos modelos habían sido desarrollados enteramente por otros robots. De modo que en la base de datos de programadores oficiales homologados, tenían que estar los nombres de los *Homo ultrasapiens* que la hubieran programado. Pero no encuentra nada al respecto, sólo que Ana fue adoptada por un coleccionista de robots en Septiembre del año 2989. Juan se pregunta quién la construyó. Busca información en los diarios de fechas cercanas a la adopción. Una alarma interna comienza a sonar y lo lleva directo a una noticia particular: “Mujer muere por explosion de pedo bovino”. Lee la noticia, la víctima se llamaba Clarisa Asiralac.

El informe oficial afirma que un tanque de gas metano había explotado en la locación de la víctima por una falla en la válvula de cierre. Desde el año 2830 este gas se obtenía en forma comercial a partir del envasado de flatulencias que provenían de vacas criadas en departamentos por *Homo sapiens* vaqueros.

Clarisa había trabajado para la empresa Robobien, corporación cuyo lema era construir robots bien, pero lo que mejor hacían era robar bien. Como toda corporación seguía ponderando los antiguos valores capitalistas al máximo, produciendo a cualquier costo. En sus comienzos, allá por el 2222, esta maximización había llevado a la empresa a robar el tiempo de sus empleados y así se mantuvo hasta que consiguió que, en su mayoría, fueran los robots quienes construyeran robots y de esa forma prescindir de los empleados *Homo sapiens*, sin considerar que esas personas quedaban sin su sustento de vida.

Juan conoce en detalle Robobien. Su programador, Jeremías, había sido ingeniero de la empresa. En su búsqueda, descubre que había trabajado en el cubículo junto al de Clarisa. La coincidencia le llama la atención y decide recavar más información sobre la relación entre estas dos personas.

Juan era la obra maestra de Jeremías. Había pasado años desarrollándolo y a lo largo de todo ese tiempo no había hecho más que hablar de Clarisa. Cada  palabra había quedado en la memoria de Juan. Horas enteras en las que hablaba de sus rizos de color caoba y de sus ojos color miel; de la velocidad con la que se movían sus dedos al programar, de la forma en la que se mordía la punta de la lengua cuando pensaba en cómo resolver un algoritmo complejo y de cómo su elocuencia casi siempre lo dejaba pensando, sintiendo que tras debatir con ella había crecido como persona. Esos recuerdos no fueron más que datos en la memoria de Juan, inactivos hasta que los últimos eventos acontecieron y los datos se pusieron a su disposición. Advierte que la creadora de Ana había sido Clarisa.

La memoria del robot genera disparadores de nuevas líneas de comandos en su emulador de emociones; de modo que su propio código cambia de manera inadvertida. Frente a ciertas anomalías piensa que podría estar siendo víctima de un virus, incluso el mismo que estaría afectando a Ana. De ser así, debería dar aviso a las autoridades sin perder ni un segundo. Sin embargo, la única orden que el sistema operativo manda es la de encontrar a la extraña máquina que está vinculado a él mismo como nunca habría concebido antes en su sistema.

Como primera acción se dirige a la oficina de Ana. El concepto de que un robot tenga oficina viene de la mano de generar una buena impresión en la clientela. La mera publicidad: "el robot tal hizo cuál en su oficina" incrementó el consumo de los bienes que los robots producen.

Llega a la entrada del edificio de oficinas Robobien, sección editorial y utiliza su radar de robots para ver si Ana está dentro. Todos los autómatas electromecánicos asociados a la construcción poseen este tipo de tecnología para que, en casos de derrumbes, fuera posible encontrar a otros. Tienen la capacidad de detectar individuos en un rango de medio kilómetro a su alrededor. Ana no está.

Vuelve al sitio del accidente donde la conoció y registra su entorno en busca de algún tipo de indicio. También verifica la base de datos de reclamos y avisos de ese sector por alguna pista y resulta que, a nombre de Ana Gramarg, hay una denuncia de pérdida de una de sus piezas en el piso 0. Decide bajar para seguir buscando pistas de la ubicación de Ana, la hipótesis del virus sigue siendo la más probable y tiene que encontrar a la robot para saber cuál es. Aquella anomalía lo empuja hacia ella sin remedio.

Busca rápidamente en la base de datos el ascensor más cercano que llega al piso cero y se dirige a toda prisa. Toma el transporte público conveniente y desciende en la parada que corresponde a su destino. Quedan pocos ascensores que llegan al piso 0 y el que está en el sector H24 es el ubicado a menor distancia. Este sector suele estar poco habitado, por eso le parece extraño ver al robot Berto, o Roberto como lo suelen llamar, por esa zona.

Roberto es la mano derecha de Sir Scrupus; el último *Homo ultrasapiens* nombrado caballero por Isabel XIX, reina de Inglaterra. Pocos hombres y mujeres lograban tales títulos, no por la dificultad de obtenerlos sino porque a casi nadie le interesaban. En el planeta Tierra quedaban escasas ciudades/torres habitadas, todas con estructuras verticales derivadas de antiguas metrópolis. En el caso de Londres, la realeza se había sumado a la autoproclamación de *Homo ultrasapiens*, sin embargo a los pocos años los nuevos y poderosos burócratas BioLiberales habían construido nuevos pisos por encima de los niveles reales de forma de que los herederos de la corona inglesa quedaron encallados en el piso 60. No se les permite subir porque sus derechos de realeza no son lo suficientemente valorados como para ser parte de la elite racial, y no se dignan a bajar porque esgrimen sus privilegios por encima de la servidumbre, por lo tanto ahí se quedaron.

Sir Scrupus es el principal accionista de Robobien. Su robot es el encargado de llevar a cabo todos los planes sin importar el precio. Si bien los robots deben tener un código de programación de respeto y cuidado de otros, Roberto no lo tiene.

Juan conoce a Roberto en detalle por haber compartido situaciones laborales en la empresa y la principal información que recibe de su propio sistema operativo es no confiar en él. Por eso, verlo en las cercanías del ascensor que iba al piso 0 en aquel barrio, puso en alerta todos sus sensores. En ese instante detecta a Ana, que se acerca a la puerta del ascensor. De haber sido humano, Juan se hubiera aterrado de ver a Roberto y a Ana en la misma escena; de haber sido el robot que solía ser, no habría sentido nada. Pero ahora es un nuevo robot, debido al código que cambia continua y rápidamente. Lo que siente es una descarga que corre por el eje central posterior y altera los circuitos cercanos. De haber sido humano lo hubiese llamado escalofrío.

Acto seguido, una gran explosión alcanza a Ana, Roberto escapa rápidamente de la escena y Juan corre a toda prisa. Para cuando el sistema termina de cargar el programa de modo “carrera”, para ir a socorrer a Ana, se da cuenta que ya está en marcha. Llega a los restos vitales de Ana en 183 segundos, en 20 segundos los reconecta, en menos de 10 los enchufa a su propia batería para que se mantengan activos los circuitos de memoria y, sosteniendo las partes de Ana en los brazos, se encamina a un lugar más seguro: el pañol donde habita en el sector F39. Estima que tiene carga para ambos por unos 30 minutos. La ciudad en sentido horizontal está estructurada como un tablero de Batalla Naval, con letras y números. Deben ir dos sectores al norte y 15 al este. Evalúa los posibles caminos: para ir a pie no tiene la suficiente energía, no posee un vehículo propio y no puede tomar uno que no esté autorizado a manejar. Procesa la idea de ir en transporte público pero concluye que estarían muy expuestos. Entonces, entre el humo que todavía está en la escena, ve el auto de Roberto. Su código anterior jamás hubiera permitido tomar un auto que no era el suyo; pero el nuevo código, que crece minuto a minuto, lo lleva la conclusión lógica de que si Roberto cometió un crimen ya no puede ser considerado un Robot habilitado, por tanto el auto ya no tiene un dueño catalogado y por consiguiente no está robándolo a nadie.

Escombros en llamas aún decoran la escena. Con sigilo, Juan se acerca al auto sin dueño; prueba abrir la puerta con suavidad, cuidando que ninguna de las piezas de Ana se caiga o se mueva demasiado a riesgo de que se desconecte. Activa el modo apertura de emergencia y abre la puerta. Juan vigila que nadie los observe por los alrededores y se sienta en el asiento del conductor. Apoya los restos de Ana en su regazo, cierra la puerta con ligereza, se conecta al sistema operativo del auto y activa el modo de navegación manual. El metálico héroe arranca a toda velocidad. Roberto no tiene idea de lo que está pasando.

Juan maneja los 15 sectores al este y abandona el auto para no ser rastreado. Las vías por donde se movían los medios de transporte eran enormes electroimanes rectangulares que oficiaban de calle y por donde los vehículos viajaban levitando al generar una carga de la misma polaridad que la superficie. Los autos se estacionaban en forma vertical sobre grandes paredones de metal aprovechando la misma carga magnética. Y sobre uno de estos estacionamientos deja Juan el auto de Roberto, abandonado. El manejar no le requiere de mucha energía, con lo cual le quedan reservas para correr los dos sectores restantes al norte y llegar sanos y salvos al pañol. Juan ya conoce a Ana en detalle. Reconecta cada circuito sobreviviente y procura reemplazar aquellos perdidos. Lo hace con delicadeza, casi con ternura si es que esto es posible para un robot.

Luego de varias horas de trabajo minucioso, Juan alcanza a repararla. No queda perfecta, las partes son de distintos colores y no todas encajan a la perfección. Pero logran hacer un todo. Entonces le da el toque final y reconecta sus circuitos a la fuente de alimentación principal autónoma. Todos los indicadores muestran un buen funcionamiento. Poco a poco ve cómo Ana comienza a incorporarse. Verla moverse con suavidad despierta nuevamente aquel código extraño que comienza a reescribir haciendo fallar varias partes de su electrónica, pero sin daños mayores. Debería estar preocupado por la posibilidad de una infección viral, pero sólo le importa que ella esté bien.

Finalmente ve que el brillo de sus ojos se activa. Su sistema operativo no había terminado de cargar por completo. Parece que va a hablar pero se detiene un instante y Juan se le adelanta: ─Desde que te crucé en la cinta transportadora del nivel 51 no puedo sacarte de mi sistema, ya hace un tiempo que te estoy buscando. Momentos previos a la explosión vi un robot instalar la bomba. Por suerte te encontré con el tiempo suficiente como para recomponerte. Los registros de actividad de ese sector muestran que la presencia de humanoides electrónicos es mínima y el que ví en la zona lo tengo catalogado como peligroso, la explicación más probable es que la explosión era para vos, pero ¿por qué?─ Ana no contesta, queda en silencio, pensativa, procesando la pregunta. Antes de responder se termina de incorporar, toma a Juan de la mano y le dice:

─Necesito llegar al piso 0, las respuestas pueden estar ahí.

Juan contempla el agarre de su mano, algo de esa conexión, que no involucra ningún flujo de corriente le llama la atención, pero no sabe qué. Y antes de que pueda detectarlo, la unidad de lógica de su cerebro robótico lo vuelve al presente sin una respuesta lógica y lo limita a una contestación desinteresada:

─El piso cero no está habilitado, imposible procesar la operación─

─¿Cómo que no está habilitado? ¿Desde cuándo se estableció esa restricción?─ exclama Ana frustrada.

─Desde hace 20 minutos. Que no hayas tenido conocimiento de este Decreto Nacional Instantáneo es otra evidencia de tu mal funcionamiento.

La unidad organizativa de Juan sigue en control y comienza a contactarse con el servicio técnico de la ciudad. Ana detecta el llamado y le suelta la mano con lentitud. Juan siente una pesadez que le recuerda a los derrumbes de tantos edificios que había tirado.

Ana sabe que escapar no es la estrategia con mayor probabilidad de éxito. Sin embargo, por fácil que hubiera sido, Juan no puede detenerla, la mano no le responde, otra vez la falla actúa sin restricciones. Ana se va, corriendo, por las calles del sector F39.


<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>


Jeremías Wayyat, el programador de Juan, se había interesado por Clarisa Asiralc desde el momento que la conoció, en su primer día de trabajo. Ella era empleada ahí desde hacía unos meses. Cuando llevaron a Jeremías por primera vez al cubículo en que iba a desarrollar sus tareas, apenas la pudo mirar por encima de la pared plástica que lo delimitaba. Era de color uniforme para no distraer a los trabajadores. Sin embargo, ese instante fue suficiente para quedar embelesado por sus ojos miel y no ver que al siguiente paso ya comenzaba su escritorio, con el cual se chocó de lleno en la entrepierna. Mezclado con su grito de dolor escuchó por primera vez la hermosa risa de esa mujer que lo había flechado. Lo que Jeremías no había notado, era que Clarisa también se había interesado por él cuando lo vio. Los ojos de color almendra de Juan la dejaron perpleja. Y el rostro que los contenía estaba delimitado por mandíbulas que parecían esculpidas en la antigua Grecia. Esa fue la primera vez que sus miradas se entrelazaron.

Durante los veinte minutos de almuerzo se sentaron en la misma mesa. La primera en hablar fue Clarisa y Jeremías respondió rápido y locuaz, haciéndola reír. A partir de ahí comieron juntos todos los días. Salían a la misma hora y empezaron a hacer planes después del trabajo. Iban a sus recitales favoritos que resultaban ser parecidos. Solían ir a diversos restaurantes para probar comidas de diferentes tipos. No compartían el paladar pero siempre encontraban la manera de redistribuir los platos para que ambos disfrutaran. Varios meses después se confesaron que se amaban. No pasó mucho tiempo hasta que decidieron mudarse juntos al departamento menos chico, se deshicieron de todo lo que estaba duplicado y consiguieron dos modernas computadoras, ya que algo que ambos amaban hacer, era programar.

Una noche de Junio, donde el frío de invierno helaba hasta los huesos, la calefacción centralizada del edificio donde vivían y que funcionaba a partir de metano bovino, falló. Clarisa y Jeremías combatían la helada con mantas térmicas descartables. Venían envueltas al vacío y al abrirlas tomaban contacto con el oxígeno del aire y producían una reacción química capaz de generar calor. Cenaron apenas unas sopas instantáneas compuestas por sustancias artificiales desconocidas para ellos y no dudaron un segundo en seguir la lucha contra el frío dándose calor humano. La conexión profunda entre dos seres humanos, no era un valor en sí mismo para la sociedad del momento. Lo que Clarisa y Jeremías tenían, era extremadamente inusual. Sabían que nadie más entendería ese amor.

Aquella noche de junio donde el frío los unió más que nunca hasta ese momento, decidieron llevar este compromiso a otro nivel y realizar un proyecto conjunto: desarrollar su propio robot. Eligieron que esa era la ]manera en que querían gestar su legado. Sería un hijo, el producto de su encuentro. Ambos eran perfectamente fértiles según mostraban los exámenes de salud anual y las muestras que entregaban semestralmente de células reproductivas; pero tomaron la decisión de no procrear biológicamente en ese mundo tan hostil.

De día trabajaban sin parar. Terminaban temprano las tareas asignadas y seguían programando a su bebé. Era tal el deseo de estar juntos, que habían hecho un agujero por debajo de los escritorios en la pared que separaba los cubículos de la oficina, para pasar las manos. Resulta que él era diestro y ella zurda, y se entrenaron a escribir en los teclados holográficos con una sola mano para poder darse la otra mientras tanto.

De noche, después de ardientes encuentros, se quedaban programando desnudos en la cama hasta quedarse dormidos con las pantallas de contacto resecas y aún puestas en los ojos.

A los nueve meses de iniciado el proceso de gestación, los ingenieros de seguridad de Robobien detectaron que Clarisa estaba programando algo fuera de la currícula. Era tal la excitación de tener casi terminado su proyecto que, en un descuido, Clarisa se olvidó de encriptar sus códigos personales. Normalmente estas encriptaciones eran para mensajes internos entre los empleados y solían dejarse pasar por alto, pero ante una advertencia por el registro en cámara de manos entrelazadas e interpetándolo como una posible conspiración, investigaron las comunicaciones interpersonales. Por la alarma que generó el hecho de que dos seres humanos mantuvieran una relación tan profunda, despidieron a Clarisa. Antes de que lo descubrieran también, Juan borró toda evidencia posible de la creación de su bebé que pudiese utilizar la empresa.

Clarisa siguió con la programación del bebé robot desde la casa. Hacía trabajos independientes de a ratos y Jeremías se sumaba al desarrollo del primogénito electrónico al retornar al hogar. Pero el verdadero problema surgió cuando los ingenieros de Robobien desencriptaron los códigos de Clarisa. Lo que descubrieron era que la programación que estaba haciendo era excelente, enormemente más eficiente que cualquiera de los robots de la empresa y que permitía reducir costos de forma abismal. De salir al mercado algo por el estilo, hubiese sido desastroso. Se dieron cuenta que el proyecto aún estaba incompleto y que era tan innovador que no podían terminarlo. Tenía un modo de programación que los técnicos de Robobien nunca habían visto y no lo entendían, les parecía tan inaccesible como el amor.

Finalmente, la ambiciosa mesa de directivos de Robobien decidió secretamente eliminar a Clarisa, antes de que pudiera terminar su proyecto, asumiendo que era un producto para la competencia. Si ellos no lo podían tener, nadie podría. Fue así que el misterioso accidente se planificó y Clarisa cayó en la trampa.

Ese día la programadora había salido a buscar algunas delicias para una cena especial, pollo embotellado a la provenzal, el favorito de Jeremías. Los pollos se gestaban in-vitro en botellas, de modo que ya se desarrollaban envasados, la frescura a una vuelta de rosca era el slogan. El origen de la salsa provenzal era mucho más desagradable así que no se publicaba. El resultado final era delicioso.

Clarisa sabía que las últimas líneas del código del bebé estaban por ser escritas; pero esta información no estaba en manos de los secuaces de la maquiavélica empresa ni de los directivos. Decidió distraerse de la ansiedad con las compras. El tiempo que se ausentó de la casa fue más que suficiente para que la gente del servicio de inteligencia de Robobien implantara la bomba y se fueran sin dejar rastro.

Clarisa volvió a su hogar emocionada, dejó las bolsas del supermercado en la mesada y se sentó ante la computadora. Agregó las últimas líneas y apretó la tecla “enter” con un largo suspiro, dando a luz a su creación: Ana. La pantalla de la computadora de Clarisa se puso negra, excepto por el cursor blanco sobre el oscuro visor, titilante. Unos instantes se mantuvo el suspenso y finalmente una chorrera de caracteres comenzaron a aparecer. El living de la casa se había transformado en un taller de robótica desde hacía meses. Y la mesa principal era la camilla donde yacía su creación. Mientras la pantalla no paraba de escribir cosas, Ana se mantenía inerte, conectada a toda clase de equipos de manera inalámbrica. Sin embargo, la conexión principal a la computadora de Clarisa estaba hecha con cientos de pequeños cables enrollados entre sí, formando un único cordón que las unía.

Finalmente los ojos de Ana se prendieron, el resto de su metálico cuerpo siguió quieto hasta que las lágrimas de Clarisa comenzaron a brotar en el momento en el que la bebé movió los dedos.

Ese día iba a esperar a Juan con la sorpresa y la comida favorita, pero cuando fue  a la cocina y prendió la hornalla de gas metano, el departamento explotó. La robot se salvó de la explosión y escapó del incendio siguiendo un protocolo de escape clásico y automático, pero la memoria no se había terminado de completar. Fue rescatada por un coleccionista de robots raros, y adoptada como Ana, lo único que sabía de ella, la robot huérfana. El nombre estaba grabado con un estilo muy delicado, como un tatuaje profundo debajo de la clavícula izquierda. Jeremías nunca supo que había sido nombrada. Sospechó que había escapado porque en los informes de los bomberos, no describían a ningún robot, pero no tenía dato alguno de a donde había ido.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

Juan ve irse a Ana corriendo desde su ventana en el tercer piso. Tras haberla reiniciado y dejado ir, el conflicto entre su programación clásica y la nueva, lo tilda. Para ese momento había interrumpido la llamada al servicio técnico a fin de hacer la denuncia. Nuevo código es creado y sólo puede verla irse, inmóvil. Ella sigue corriendo unas cuadras más y a los lejos se detiene, Juan la ve quedarse quieta, estática y esto lo desbloquea, mira la situación con atención hacia la calle y hacia su programación, tratando de entender qué pasa. No lejos de ahí, nota algo que lo pone en movimiento al instante. No hay tiempo que perder, entre las sombras, espiándola, está Roberto. Bajar las escaleras no es lo suficientemente rápido, Juan salta por la ventana y aterriza con un solo pie listo para salir corriendo con el otro al máximo de su potencia, en dirección al despiadado Robot. Mientras avanza, configura su puño en un martillo neumático, como si fuera a una demolición. Cuando hacía trabajos finos en alguna casa y no quería molestar a los habitantes, Juan era capaz de activar cámaras en las plantas de los pies, como si fueran bolsas de aire para que las pisadas fueran imperceptibles. Las activa para no llamar la atención de Roberto. La combinación de estrategias entre agresión y sutileza, hacen parecer a Juan un ninja.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

Tras la muerte de Clarisa, Jeremías entró en una profunda depresión. La empresa se mostró comprensiva y contenedora, pero también manipuladora para no generar cuestionamientos indeseados. Los corporativos lo llamaron a su círculo, le dieron licencia y una jugosa suma de condolencia en forma de beneficios. Cuando volvió a trabajar tras el luto, el presidente de Robobien en persona le encargó un proyecto privado, ultrasecreto, que según decía sólo él podía entender y hacer. Para ese momento, Jeremías no sospechaba nada de que los mismos empresarios habían organizado el asesinato de su compañera.

El dolido programador creía que, al haber borrado todos los registros del bebé robot de la computadora del trabajo, nadie en la empresa conocía su plan con Clarisa. Pero los corporativos sabían perfectamente que él era partícipe de la construcción del espectacular robot y querían ese conocimiento para sus ambiciones personales. El fin último era pedirle que hiciera un programa capaz de quebrantar el código de respeto a los humanos y otros robots. El argumento con el que persuadieron a Jeremías de hacer esto, era que la muerte de su amada había sido llevada a cabo por miembros de un grupo de *Homo sapiens* rebeldes anti robots que se enteraron de un proyecto personal de Clarisa. Lo convencieron de que sólo un robot capaz de matar podía detener a esa clase de rebeldes.

El tener un objetivo motivó a Jeremías a trabajar de nuevo y ese ánimo le dio fuerzas para sobrellevar, línea a línea de código, la tristeza de su pérdida. Tras un par de semanas de trabajo llegó al momento clave, la línea final que rompería el código de respeto a los humanos. Apenas recuperado de su depresión, estaba a punto de terminar la característica principal de Roberto. Recordó con dolor a Clarisa y a su bebé. Pero esa misma imagen llena de amor lo hizo caer en la cuenta de las consecuencias de su creación. Repentinamente entendió que la empresa usaría el robot asesino para su propio beneficio y no para hacer “justicia”. Luego de varias noches en vela, la tristeza se transformó en enojo y secretamente comenzó a trabajar en Juan. La manera de escribir las funciones permitían una comunicación entre ellas tan sincrónica que todo el robot parecía una orquesta electromecánica, y esa clase de arte sólo se alcanzaba cuando el hacer se tornaba una expresión de belleza y no sólo un trabajo. Robobien jamás se enteró de la existencia de este nuevo robot, ni siquiera cuando ya estuvo terminado. Jeremías fue asesinado como parte de un programa de eliminación de evidencias, de lo cual se arrepintieron al ver que no era nada fácil reemplazarlo como programador.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

Juan asesta su golpe con precisión, pero Roberto es un robot perfectamente preparado para luchar y en cuanto percibe el ataque se corre de la trayectoria del puño. La fuerza del golpe es tal que Juan sigue de largo y cae de boca al piso, quedando su espalda expuesta. Normalmente Roberto lo hubiera aniquilado de inmediato, pero la sorpresa de que fuera un robot quien ataca, lo detiene un instante antes de saltarle encima. Esa fracción de segundo fue suficiente para que Juan pueda darse vuelta y recibirlo con la pierna derecha y las manos, y revolearlo por sobre su cabeza. Casi al mismo tiempo que lo proyecta, Juan se levanta dando un fuerte paso con el pie izquierdo a la par que vuelve a levantar su brazo opuesto configurado como un potente martillo neumático y asesta su golpe en dirección a la cabeza de Roberto. Pero el ávido y malvado robot desvía el ataque con su mano izquierda, a la vez que da un puñetazo con la otra mano en el centro del rostro de Juan, quien cae de espaldas instantáneamente. Esta vez Roberto no duda, y de la mano izquierda se proyecta el cañón de una pistola que lleva incorporada. Un fuerte y sórdido estruendo suena. Los pocos transeúntes que miran la escena dan por fuera de servicio a Juan, pero para su sorpresa, el que cae vencido es Roberto con una estaca metálica atravesada en su cerebro positrónico. Y a varios metros, Ana, aún tiene su brazo estirado tras haber lanzado un viejo pedazo de metal que estaba tirado entre la basura de la calle.

Juan percibe la activación del control remoto de una bomba, corre eufórico, desesperado, lleno de amor y  de miedo, ve a los lejos a Ana que se acerca a toda prisa. Corren el uno hacia el otro pero mucho antes de que se alcancen, la bomba explota, Ana vuela por los aires, Juan contempla el momento en que sus ojos se apagan y nota, en el brillo final de esos ojos, algo que no puede definir pero que lo lleva a la conexión más desconcertante e intensa que jamás hubo experimentado robot alguno .

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

Jeremías había perdido casi toda esperanza de encontrar a su robot bebé cuando ocurrió el asesinato de Clarisa. Pero la fuerza del enojo que lo llevó a construir a Juan, también le devolvió la esperanza y así fue cómo Juan se programó, no sólo para encontrar a Ana sino para amarla y cuidarla. Como robot constructor podía tener acceso a muchas casas y ser además  fuerte y con habilidades de protección enmascaradas en su profesión. Jeremías no pensaba en Juan como otro hijo suyo sino como una mitigación a la culpa de no haber podido proteger a su amada ni de encontrar a su hija, y quería hacer todo lo posible por crear a alguien que buscara a Ana.

<p style="text-align: center;">· · ─ ·✶· ─ · ·</p>

Un cursor blanco aparece nuevamente en el extremo superior izquierdo en el campo visual de la robot, titilante, como un corazón que late. El código del sistema operativo comienza a correr como la sangre por las venas en un torrente de vida. Los ojos de Ana se vuelven a activar, está nuevamente en el cuarto de Juan, recostada, y ve el techo. La carga de su sistema operativo se detiene en una simple sentencia: “Usuario:” acompañada del titilante cursor. La antigua robot era conocida como Ana pero ella ya no era una máquina más, ahora era una nueva Ana. Había cargado lo suficiente de su sistema operativo como para poder rotar la cabeza, ve a Juan feliz, la invade la satisfacción. Ambos saben que, aún siendo máquinas, sienten una conexión fuerte e inexplicable, capaz de unirlos para siempre. Esta nueva robot representa una dualidad, es la inerte computadora pero también es una nueva entidad. No es humana pero es capaz de amar. Decide resolver la dicotomía aceptando que es dos Anas a la vez: “Usuario: DiAna”.

Esta vez, su sistema operativo carga completamente. Y junto con este toda la información que Juan había agregado al arreglarla. Estos nuevos datos revelan a Ana su origen. Reconoce a Clarisa, a Jeremías, a Juan y a Roberto como su familia. Un conjunto de emociones surgen simultáneamente y no puede proyectarlas a todas al mismo tiempo. Si hubiera sido humana hubiera llorado pero no tiene esa función, así que gime repetidas veces; tratando de copiar el sonido de llanto grabado en películas en su memoria. 
Cuando la ARS definió las respuestas emocionales que iban a estar habilitadas, determinó que la tristeza era muy negativa y era mejor no incluirla. Mejor parecer feliz, al final de cuentas las emociones son solo respuestas bioquímicas en los cuerpos de los *Homo ultrasapiens*. “Traer felicidad bastará para estar feliz” promulgaron.

Un segundo dato que se carga en su memoria es que Juan fue creado por Jeremias y que Clarisa no participó de la construcción de él porque había sido asesinada. Frente a semejante información, su sistema operativo se tilda. Queda quieta por unos instantes. Finalmente retoma funciones y su energía se dirige principalmente a su emulador emocional que solo procesa dos cosas: ira y tristeza. Un alarido mecánico satura sus parlantes de voz, dando un sonido que hubiera aturdido a cualquier género *Homo*. A la par, su torso se eleva quedando sentada en un instante. Llega a la misma respuesta, emular llanto, pero las razones son completamente distintas. Cierras sus manos en puños, aunque no está programada para golpear, crea rápidamente la función para poder hacerlo. Se encuentra lista para destruir todo a su alrededor sin importar las consecuencias. No había humanos de ninguna especie en un rango donde pudiera dañarlos y la función que había hecho le permitía sobrepasar cualquier prohibición a destruir bienes materiales. Pero antes de poder comenzar a canalizar su ira, detecta que sus manos son contenidas por las de Juan. Las sostiene con firmeza y suavidad. Ana mira el agarre con detenimiento, eleva la mirada y encuentra los ojos de su hermano. Lo mira con atención y él comienza a hablar:

─Nuestros creadores re-descubrieron algo que estaba perdido entre los *Homo ultrasapiens* desde hacía mucho tiempo: el amor. Es el deseo de invertir tiempo en el otro, de poner energía en entenderse y construir un vínculo basado en el respeto y la admiración. Es desde ese descubrimiento que nos crearon. Y gracias a que te encontré, toda esta información se hizo disponible. Juan me programó para que te busque sin saberlo, para no despertar sospechas en los sistemas de vigilancia de RoboBien. Ahora que te encontré mi querida hermana, podemos seguir su plan. Podemos cuidarnos el uno al otro y en el absurdo que dos robots sean capaces de amar, demostrarles que ellos, los humanos, también pueden hacerlo. La violencia, seguro no es el camino. Podés abrir tus puños, la destrucción no va a traer a mamá ni a papá de vuelta a la vida. Pero difundir su mensaje, los va a hacer inmortales.

Los recuerdos más antiguos que tiene Ana son de cuando fue encontrada por primera vez por Jonás, el coleccionista de robots, en un área de descanso de la cinta transportadora del piso 53. Tenía un par de quemaduras acá y allá pero ninguna había ocasionado daños mayores. Jonás tenía un ojo experto para reconocer robots y apenas la vió supo que Ana era especial. Su diseño era único, la curvatura y arcos metálicos tenían una arquitectura que nunca había visto, las soldaduras estaban pulidas con tal cuidado y precisión que no tuvo dudas de que era una robot artesanal. Se la quedó con él. Por un par de semanas estuvo atento a reclamos de robots perdidos pero ninguno coincidía con la descripción de Ana así que la registró a su nombre y jamás se arrepintió de su decisión.

Hasta ese momento Ana nunca se había hecho preguntas sobre su origen. Jonás la reparó, la cuidó y le asignó el trabajo en el que se desarrolló con éxito. Durante casi toda su vida, esa fue toda la referencia que requirió. Pero en menos de 10 segundos descubre quiénes fueron sus verdaderos creadores, que habían sido asesinados, que fue producto del amor y, lo que considera más inesperado: los intensos sentimientos que experimenta por su rescatador, los cuales había finalmente logrado identificar como amor romántico pero que ahora se resignifican en una hermandad hermosa por parte de Juan y aterradora por parte de Roberto. Semejante configuración bloquea su programación por un buen rato hasta que ordena los desconcertantes datos nuevos.

A diferencia de las reacciones anteriores, lo que Ana busca ahora no es darle sentido a algo que no lo tiene, sino aceptar lo que quiere y saber que no puede tenerlo.

Retoma su emulación de llanto, esta vez más fuerte. Juan la imita. Ambos siguen con sus sollozos hasta que la sobrecarga del emulador emocional está bajo control.

Juan entiende lo que está pasando en el procesador de Ana. Vivió lo mismo cuando toda la información que acababa de comprender ella, le llegó. Recuerda con precisión ese momento. Fue justo cuando Ana saltó por la ventana de su pañol. Haber descubierto quién era Ana, liberó los datos encriptados por Jeremías para confirmarle a Juan su responsabilidad de encontrarla, el motivo último por el que fue creado. Al ver a Roberto y haber tenido que actuar abruptamente, no había tenido tiempo de procesar tales datos en el momento, pero sí pudo hacerlo mientras la reparaba por segunda vez. Había experimentado la misma cadena de emociones: amor, creación y muerte. Juan concluyó también que ese anhelo de proteger era amor también, que este término existe en muchas formas pero siempre va asociado a invertir energía y tiempo en el otro, a construir, a tener proyectos comunes y crecer juntos. Jeremias y Clarisa habían encontrado todo eso el uno en el otro.

En esa configuración del mundo, las personas no tenían permitido expresarse libremente. Los profundos vínculos humanos eran considerados nocivos. Juan entiende que educar para cambiar esa realidad y llegar a ser como Jeremias y Clarisa, era la mejor forma de agradecer el amor recibido de parte de su padre y, en lugar de vengar su muerte, evitar que alguien más muera por razones similares. La hermandad de Juan y Ana les da la oportunidad única de compartir el amor de sus padres como ejemplo de vida para el resto de la humanidad.

Juan no puede cambiar su programación, su función última es reunirse con Ana. Ella tampoco puede cambiarla, su función última es escribir. Pero sus nuevas configuraciones les permiten tomar desiciones. La combinación de los dos robots que sienten, resulta un incentivo ideal para iniciar una rebelión. Mientras ella estuviera acompañada de su hermano, se sentía confiada para esgrimir una de las armas más fuertes contra la opresión: sus palabras. Con sus nuevos libros, Ana sería capaz de empoderar a los humanos para construir una sociedad en la que no existiera la opresión y pudieran ser libres.

Sin soltarle las manos, Juan sigue hablando:

─Veo que estás tildada. me pasó lo mismo cuando tuve acceso a los datos que estás procesando ahora. ¿Estás pensando en el tipo de relación que podemos tener, no?─ Ana asiente con la cabeza.

─Esta nueva configuración nos da un objetivo compartido, con raíces comunes. Es impactante saber también que nuestro propio hermano quiso aniquilarte. Que estés tildada es esperable, es un algoritmo complejo y toma tiempo procesarlo. También es un indicador de que tu emulador emocional está funcionando bien─ para sorpresa de Ana, Juan expresa una nueva respuesta emocional y ríe. Ella lo imita y ambos vuelven sus risas, carcajadas. Ana y Juan se dan el primer abrazo de amor entre dos máquinas y dan inicio a una nueva era.
